server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dkfjkjg/SpringcloudConfig #配置文件所在仓库
          username: dkfjkjg
          password: password
          default-label: main #配置文件分支
          search-paths: respo  #配置文件所在根目录
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/