server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://root:123456@${eureka.instance.hostname}:${server.port}/eureka/
spring:
  security:
    user:
      name: root
      password: 123456