
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8752/eureka/,http://peer1:8751/eureka/
server:
  port: 8762

spring:
  application:
    name: service-hi
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1